Release Lesson #1
cuurjol/thinknetica-js-course pull request #1
Opened 2022-07-03 22:28 UTC by cuurjol

https://thinknetica.teachbase.ru/course_sessions/469919/tasks/230675/take?return_url=/viewer/sessions/469919/tasks/230675

2022-07-05 23:58 UTC, PonomareVlad requested changes
Нужно уточнить решение задания **1**

2022-07-05 23:58 UTC, PonomareVlad commented on lessons/lesson-1/tasks/task-5.js
> +}
В таком выражении можно исключить дополнительные скобки, т.к. вы проверяете соответствие всех условий без исключений:
```suggestion
function checkAccess(user) {
  if (user['isAdmin'] && user['age'] >= 18 && user['age'] <= 35) {
    return true
  } else if (user['age'] >= 18 && user['age'] <= 35 && user['paid'] && !user['blocked'] && !user['badUsername']) {
    return true
  } else {
    return false
  }
}
```

2022-07-05 23:58 UTC, PonomareVlad commented on lessons/lesson-1/tasks/task-6.js
> +}
Попробуйте также исключить лишние скобки для этого выражения

2022-07-05 23:58 UTC, PonomareVlad commented on lessons/lesson-1/tasks/task-1.txt
> +e) x = ((x + y) - ((x++) * z));
Уточните пожалуйста, каким шагом будет обрабатываться оператор `x += ...` ?

2022-07-06 20:06 UTC, cuurjol commented on lessons/lesson-1/tasks/task-5.js
> +}
Исправил.

2022-07-06 20:06 UTC, gwynolanga commented on lessons/lesson-1/tasks/task-6.js
> +}
@PonomareVlad Исправил.

2022-07-06 20:07 UTC, cuurjol commented on lessons/lesson-1/tasks/task-1.txt
> +e) x = ((x + y) - ((x++) * z));
Переписал по-другому порядок операций.

2022-07-08 09:17 UTC, PonomareVlad approved these changes
Отлично 🎉

2022-07-09 12:53 UTC, merged