Release Lesson #2
cuurjol/thinknetica-js-course pull request #2
Opened 2022-07-10 18:55 UTC by cuurjol

https://thinknetica.teachbase.ru/course_sessions/469919/tasks/230676/take?return_url=/viewer/sessions/469919/tasks/230676

2022-07-11 09:12 UTC, PonomareVlad requested changes
Нужно исправить решения заданий **1**, **2**, **8**

2022-07-11 09:12 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-1.js
> +}
[Результат вызова функции с текстом на кириллице](https://thinknetica.ponomarevlad.ru/2/1.html?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcuurjol%2Fthinknetica-js-course%2Fcuurjol-part-2%2Flessons%2Flesson-2%2Ftasks%2Ftask-1.js&func=wordStatistics#cyrillic)

2022-07-11 09:12 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-2.js
> +}
[Результат вызова функции с массивом, в котором есть пустые элементы](https://thinknetica.ponomarevlad.ru/2/2.html?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcuurjol%2Fthinknetica-js-course%2Fcuurjol-part-2%2Flessons%2Flesson-2%2Ftasks%2Ftask-2.js&func=eqlTwoArrays#empty)

2022-07-11 09:12 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-5.js
> +}
На всякий случай уточню, что обращаться к свойствам объекта можно без конструкции `obj['...']` (такой формат используется если имя свойства нужно вычислить `obj['color_' + colorName]`)

```suggestion
function avgSalary(employees) {
	let amount = employees.reduce((acc, employee) => (acc + employee.salary), 0);
	return amount / employees.length;
}

function sortBySalary(employees) {
	return employees.sort((employee1, employee2) => (employee1.salary - employee2.salary));
}

function filterEmployees(employees) {
	return employees.filter((employee) => (employee.salary > 4500 && employee.age > 25));
}
```

2022-07-11 09:12 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-6.js
> +}
Метод `Array.sort()` выполняет один цикл сопоставления пар элементов массива, таким образом мы можем не сохранять порядок сортировки перед его вызовом, а полностью отдаться на волю случая 🙂

```suggestion
function shuffle(array) {
	return [...array].sort(() => 0.5 - Math.random())
}
```

2022-07-11 09:12 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-8.js
> +	},
[Если человек укажет только имя, то геттер выводит undefined](https://thinknetica.ponomarevlad.ru/2/8.html?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcuurjol%2Fthinknetica-js-course%2Fcuurjol-part-2%2Flessons%2Flesson-2%2Ftasks%2Ftask-8.js#name)

2022-07-11 09:12 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-8.js
> +	}
Обратите внимание на формулировку задания:

> 3. При задании значения свойства dateOfBirth должно **_так же_** устанавливаться свойство age в зависимости от разницы года рождения и текущего года

В данный момент ваш сеттер **_только_** пытается установить возраст в свойство age, путем вычитания **_даты из года_**:

```js
this.age = (new Date()).getFullYear() - value
// Выглядит примерно так
this.age = 2022 - '01.01.2000' // NaN
```

2022-07-14 05:58 UTC, cuurjol commented on lessons/lesson-2/tasks/task-1.js
> +}
@PonomareVlad Исправил.

2022-07-14 05:58 UTC, cuurjol commented on lessons/lesson-2/tasks/task-2.js
> +}
@PonomareVlad Исправил.

2022-07-14 05:58 UTC, cuurjol commented on lessons/lesson-2/tasks/task-5.js
> +}
@PonomareVlad Исправил.

2022-07-14 05:58 UTC, cuurjol commented on lessons/lesson-2/tasks/task-6.js
> +}
@PonomareVlad Исправил.

2022-07-14 05:58 UTC, cuurjol commented on lessons/lesson-2/tasks/task-8.js
> +	},
@PonomareVlad Исправил.

2022-07-14 05:58 UTC, cuurjol commented on lessons/lesson-2/tasks/task-8.js
> +	}
@PonomareVlad Исправил.

2022-07-14 09:35 UTC, PonomareVlad requested changes
Нужно уточнить решение **8-й** задачи

2022-07-14 09:35 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-8.js
> +			return new Date(`${new Date().getFullYear() - this.age}`).toLocaleDateString('ru')
@cuurjol можете пожалуйста рассказать, что происходит в этой строке ? 🙂

2022-07-14 09:35 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-8.js
> +			}
Полагаю, что так будет удобнее, в случае если потребуется также вывести еще и отчество:

```suggestion
			return [this.firstName, this.lastName].filter(Boolean).join(' ')
```

2022-07-14 10:19 UTC, cuurjol commented on lessons/lesson-2/tasks/task-8.js
> +			return new Date(`${new Date().getFullYear() - this.age}`).toLocaleDateString('ru')
@PonomareVlad Создаётся дата, параметр который является строка, содержащая число (год), и полученная дата преобразуется в строку формата `dd.MM.yyyy`.

2022-07-14 10:21 UTC, gwynolanga commented on lessons/lesson-2/tasks/task-8.js
> +			}
@PonomareVlad Исправил.

2022-07-14 10:42 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-8.js
> +			return new Date(`${new Date().getFullYear() - this.age}`).toLocaleDateString('ru')
Хорошо, а в полученной строке формата `dd.MM.yyyy` — день и месяц будут соответствовать тем, которое были переданны при установке даты ?

```js
human.dateOfBirth = "22.02.2022"

console.log(human.dateOfBirth) // ?
```

2022-07-14 10:54 UTC, cuurjol commented on lessons/lesson-2/tasks/task-8.js
> +			return new Date(`${new Date().getFullYear() - this.age}`).toLocaleDateString('ru')
@PonomareVlad Нет, не будут. Тогда к вам следующий вопрос. Почему в последнем вашем тесте, где вы делаете `human.dateOfBirth = '1/1/2000';`, в переменной `date = human.dateOfBirth` вдруг возвращается результат в формате `dd.MM.yyyy`? У вас же с самого начала формат иностранный. Я могу примерно такое сделать:
```
set(value) {
	this._dateOfBirth_ = value
	this.age = new Date().getFullYear() - new Date(value).getFullYear()
}
```
Но тогда не понятно, зачем тогда нужен getter `dateOfBirth`, когда у меня есть доступ напрямую к `_dateOfBirth_`. Более того, если я сделаю следующий getter:
```
get() {
	return this._dateOfBirth_
}
```

То у меня будет возвращать ту дату в виде строки, которую передали при вызове setter `dateOfBirth`, то есть, `1/1/2000`. Но при этом у вас возвращается результат даты в `ru` локале....

2022-07-14 11:01 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-8.js
> +			return new Date(`${new Date().getFullYear() - this.age}`).toLocaleDateString('ru')
Этот тест был предназначен для решения другого ученика, в котором мы проверяли баг браузера Safari, из-за которого автоматический парсинг даты не распознает локаль `ru-RU` и выводит `Invalid Date`

2022-07-14 11:03 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-8.js
> +			return new Date(`${new Date().getFullYear() - this.age}`).toLocaleDateString('ru')
Я указал на отсутствие геттера по причине того что вы не сохраняли данные о дате (помимо возраста)

2022-07-14 11:06 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-8.js
> +			return new Date(`${new Date().getFullYear() - this.age}`).toLocaleDateString('ru')
Насчет поддержки определенных локалей, требования в задаче нет, таким образом вы можете хранить как объект даты, так и строковое представление в любом формате — это будет корректно, при условии что его можно будет как записать так и прочитать из одного свойства

2022-07-14 11:23 UTC, gwynolanga commented on lessons/lesson-2/tasks/task-8.js
> +			return new Date(`${new Date().getFullYear() - this.age}`).toLocaleDateString('ru')
@PonomareVlad В общем, я обновил через force последний коммит, возможно надо было так делать, я не знаю. И я всё равно не понял по поводу этого последнего теста, нужно ли мне что-то с этим делать или нет?

2022-07-14 11:27 UTC, PonomareVlad commented on lessons/lesson-2/tasks/task-8.js
> +			return new Date(`${new Date().getFullYear() - this.age}`).toLocaleDateString('ru')
Нет, если эти тесты я не упомянул то они не подходят для вашего решения 🙂

2022-07-14 11:29 UTC, PonomareVlad approved these changes
Решения по всем заданиям приняты 🎉

2022-07-14 16:25 UTC, merged