Release Lesson #3
cuurjol/thinknetica-js-course pull request #3
Opened 2022-07-18 06:49 UTC by cuurjol

https://thinknetica.teachbase.ru/course_sessions/469919/tasks/230677/take?return_url=/viewer/sessions/469919/tasks/230677

2022-07-18 10:22 UTC, PonomareVlad commented
В ответ на ваш вопрос про точки с запятой, предлагаю ознакомиться с этими материалами:

https://learn.javascript.ru/structure#semicolon
https://learn.javascript.ru/javascript-specials
https://learn.javascript.ru/coding-style

2022-07-18 11:08 UTC, gwynolanga commented
@PonomareVlad я прочитал ваши ссылки, спасибо. Нужно ли мне сейчас в своих заданиях проставить `;` или не стоит? Так-то я сделал все задания для 3 урока, жду от вас code review.

2022-07-18 11:10 UTC, PonomareVlad commented
Ревью в процессе, сообщите, если планируете внести правки в код

2022-07-18 11:11 UTC, gwynolanga commented
@PonomareVlad Не планирую вносить правки. Правки будут после вашего code review, если необходимо будет.

2022-07-18 16:02 UTC, PonomareVlad requested changes
Нужно доработать решения для задач **2**, **3**, **4**

2022-07-18 16:02 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-1.js
> +	}
Однострочные стрелочные функции можно записать компактнее:

```suggestion
	this.addCoin = () => ++coins
	this.getAmount = () => coins
```

2022-07-18 16:02 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-2.js
> +}
> Функция должна запоминать аргументы, которые она уже получала ...

Функция не кэширует все расчеты, а только последний:

```js
const test = cache()

console.debug(test(1, 1)) // {value: 1, fromCache: false}
console.debug(test(1, 1)) // {value: 1, fromCache: true}
console.debug(test(1, 2)) // {value: 1, fromCache: false}
console.debug(test(1, 1)) // {value: 1, fromCache: false}
```

2022-07-18 16:02 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-3.js
> +	}
Проверьте работу функции с отрицательными значениями:

```js
const test = new Calc()

test.operation('1 + -1') // NaN
```

2022-07-18 16:02 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-3.js
> +		let method = methods.find((method) => (method.name === method_name))
Лучше избегать переборов массива через `Array.find()` если поиск выполняется только по одному уникальному ключу, и использовать вместо этого, например, объекты:

```js
const methods = {/* ... */}

let method = methods[method_name]
```

2022-07-18 16:02 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-4.js
> +	}
Можно ли как-то избежать переборов массивов в этих функциях ?

2022-07-18 16:02 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-4.js
> +	}
Судя по тому, что вы меняете цену только у первого найденного мероприятия в массиве, можно предположить, что названия мероприятий уникальны — в таком случае можно упростить код и хранить данные о мероприятиях в объекте, где ключами будут являться их уникальные названия

2022-07-18 16:02 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-4.js
> +			ticketId++
> ... возвращаем случайный **шестизначный** ID билета, создать ID можно любым способом

2022-07-18 16:02 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-4.js
> +	}
Т.к. вы используете [`Array.find()`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find) для поиска билета, то можно удалить элемент из массива более эффективным способом, запомнив его индекс:

```js
let index;

let soldTicket = soldTickets.find((ticket, i) => {
    const result = ticket.id === parseInt(ticketId));
    if (result) index = i;
    return result;
});

delete soldTickets[index];
```

2022-07-18 16:20 UTC, gwynolanga commented on lessons/lesson-3/tasks/task-4.js
> +	}
@PonomareVlad Ну если только не создавать этих функций, то есть, убрать их. Тут идея в том, что если просто вернуть массив объектов, то снаружи я смогу этот массив объектов как угодно видоизменить и эти изменения будут также затронуты и внутри моей функции. То есть другими словами, снаружи я буду ссылаться на один и тот же массив объектов. К тому же, внутри массива объекты тоже будут ссылаться на объекты, которые ранее были созданы внутри моей функции. И у меня нет других идей, как избежать пересоздания нового массива с пересозданными внутри объектами.

2022-07-18 17:23 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-4.js
> +	}
Перечисленные вами проблемы, можно решить с использованием [сеттеров](https://learn.javascript.ru/property-accessors) или [прокси](https://learn.javascript.ru/proxy) на дочерних объектах, однако это неизбежно добавит кода в моменте их объявлеия

2022-07-18 18:48 UTC, cuurjol commented on lessons/lesson-3/tasks/task-1.js
> +	}
@PonomareVlad В вашем варианте кода на 23 строчке будет возвращено значение `coins` после выполнения метода `addCoin`. В моём варианте возвращается `undefined`. Можно ли как-то в одну строчку сделать так, чтобы тоже возвращалось значение `undefined`? Другой вопрос: имеет ли смысл в данной ситуации вообще возвращать значение `undefined`?

2022-07-18 19:11 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-1.js
> +	}
Зависит от вашей реализации 🙂

Иногда удобно получить сразу результат вычисления, без дополнительного обращения к переменной или вызова функции

Однако, если вы хотите возвращать именно `undefined`, то можно сделать так:

```js
this.addCoin = () => (++coins, undefined)
```

[Подробности](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Comma_Operator)

P.S. Не рекомендую часто использовать этот трюк, т.к. это сильно снижает читабельность кода + некоторые команды (компании) будут против подобного стиля написания кода и попросят переписать это так, как вы написали изначально (используя мультистрочный формат)

2022-07-19 10:22 UTC, cuurjol commented on lessons/lesson-3/tasks/task-1.js
> +	}
@PonomareVlad Исправил.

2022-07-19 10:22 UTC, cuurjol commented on lessons/lesson-3/tasks/task-2.js
> +}
@PonomareVlad Исправил.

2022-07-19 10:22 UTC, cuurjol commented on lessons/lesson-3/tasks/task-3.js
> +	}
@PonomareVlad Исправил.

2022-07-19 10:23 UTC, cuurjol commented on lessons/lesson-3/tasks/task-3.js
> +		let method = methods.find((method) => (method.name === method_name))
@PonomareVlad Исправил.

2022-07-19 10:23 UTC, cuurjol commented on lessons/lesson-3/tasks/task-4.js
> +	}
@PonomareVlad Исправил.

2022-07-19 10:23 UTC, cuurjol commented on lessons/lesson-3/tasks/task-4.js
> +			ticketId++
@PonomareVlad Исправил.

2022-07-19 10:24 UTC, cuurjol commented on lessons/lesson-3/tasks/task-4.js
> +	}
@PonomareVlad Немного переделал решение - использую только Хэши.

2022-07-19 10:30 UTC, cuurjol commented on lessons/lesson-3/tasks/task-4.js
> +	}
@PonomareVlad  Я всё равно не понял, как нужно по итогу решить мою проблему через сеттеры (возможно вы имели в виду геттеры, а не сеттеры) или прокси (прокси пока что для меня сложно, не совсем я там всё понял).

https://stackoverflow.com/questions/597588/how-do-you-clone-an-array-of-objects-in-javascript - вот здесь я смотрел примеры других людей, как они делают. И я точно также примерно сделал для себя.

Если как-то попробовать для 4 задания сделать через сеттер (возможно геттер, я просто вас не понял), то я просто добавил следующий фрагмент кода в мою функцию:
```
  this.hello = {
    get() {
      return Object.assign({}, availableTickets)
    }
  }

  this.world = {
    get() {
      return Object.assign({}, soldTickets)
    }
  }

// В консоле node:
> const ticketWindow = new TicketWindow()
undefined
> ticketWindow
TicketWindow {
  hello: { get: [Function: get] },
  world: { get: [Function: get] },
  cash: [Function (anonymous)],
  availableTickets: [Function (anonymous)],
  soldTickets: [Function (anonymous)],
  createEvent: [Function (anonymous)],
  buyTicket: [Function (anonymous)],
  returnTicket: [Function (anonymous)]
}
> ticketWindow.hello
{ get: [Function: get] }
> ticketWindow.hello.get
[Function: get]
> ticketWindow.hello.get()
{}
> 
```

То есть, у меня получается какой-то сложный сеттер (возможно геттер, я просто вас не понял), что приходится сложным способом вызывать через `.hello.get`....

2022-07-19 10:46 UTC, cuurjol commented on lessons/lesson-3/tasks/task-4.js
> +	}
@PonomareVlad В общем, если кратко, то я хочу понять, получится ли тоже самое (геттеры/сеттеры) сделать в замыканиях, как если бы я работал с объектом через Object.create() или это невозможно. У меня вот сейчас не совсем это получилось. Возможно сейчас для этого урока не нужно, а понадобится мне это чуть позже в других уроках.

2022-07-19 12:53 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-4.js
> +	}
@cuurjol предлагаю тогда вынести текущий вопрос за рамки этого задания, постараюсь ответить на него отдельно чтобы не замедлять вас

2022-07-19 13:06 UTC, gwynolanga commented on lessons/lesson-3/tasks/task-4.js
> +	}
@PonomareVlad Да, хорошо. Я данную ситуацию решил просто рассмотреть в рамках этих заданий. Вдруг в дальнейшем мне это понадобится.

2022-07-19 14:15 UTC, PonomareVlad requested changes
Нужно доработать решения заданий **3** и **4**

2022-07-19 14:15 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-2.js
> +		let calculation = historicalCalculations.find((calc) => calc.number === number && calc.degree === degree)
Отмечу, что с каждой новой операцией, время на поиск кэшированных расчетов через `Array.find()` будет линейно расти

Рекомендую использовать либо вложенные массивы/объекты (`historicalCalculations[x][y] = result`) либо составные ключи в объекте (`historicalCalculations[x + '_' + y] = result`)

2022-07-19 14:15 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-3.js
> +		let operands = expression.match(/-?\d+/g).map((item) => parseFloat(item))
Проверьте работу с дробными числами:

```js
console.debug(new Calc().operation('1 - 0.5')) // NaN
```

2022-07-19 14:15 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-4.js
> +			let ticketId = Math.floor(Math.random() * 900000) + 1
Проверьте длину ваших идентификаторов:

```js
const ticketId = () => Math.floor(Math.random() * 900000) + 1

const test = Array(100).fill().map(() => String(ticketId()).length)

console.debug('ID length', {min: Math.min(...test), max: Math.max(...test)})
```

2022-07-19 14:15 UTC, PonomareVlad commented on lessons/lesson-3/tasks/task-4.js
> +			return availableTickets[ticketName]
Предлагаю парсить идентификатор билета один раз и повторно использовать его:
```suggestion
		const id = parseInt(ticketId)
		const ticketName = soldTickets[id]
		if (ticketName) {
			cash -= availableTickets[ticketName]
			delete soldTickets[id]
			return availableTickets[ticketName]
```

2022-07-19 15:57 UTC, cuurjol commented on lessons/lesson-3/tasks/task-2.js
> +		let calculation = historicalCalculations.find((calc) => calc.number === number && calc.degree === degree)
@PonomareVlad Исправил.

2022-07-19 15:57 UTC, gwynolanga commented on lessons/lesson-3/tasks/task-3.js
> +		let operands = expression.match(/-?\d+/g).map((item) => parseFloat(item))
@PonomareVlad Исправил.

2022-07-19 15:57 UTC, cuurjol commented on lessons/lesson-3/tasks/task-4.js
> +			let ticketId = Math.floor(Math.random() * 900000) + 1
@PonomareVlad Исправил.

2022-07-19 15:57 UTC, cuurjol commented on lessons/lesson-3/tasks/task-4.js
> +			return availableTickets[ticketName]
@PonomareVlad Исправил.

2022-07-19 16:02 UTC, PonomareVlad approved these changes
Все хорошо 👍🏻

2022-07-19 19:56 UTC, merged