Release Lesson #4, task #2
cuurjol/thinknetica-js-course pull request #5
Opened 2022-07-22 08:15 UTC by cuurjol

https://thinknetica.teachbase.ru/course_sessions/469919/tasks/230679/take?return_url=/viewer/sessions/469919/tasks/230679

2022-07-22 14:18 UTC, PonomareVlad requested changes
Нужно доработать решение задачи

2022-07-22 14:18 UTC, PonomareVlad commented on lessons/lesson-4/tasks/task-4.js
> +		if (this.type === 'MotorShipYard' || this.type === 'SailingShipShipYard') {
> Проверка типа корабля должна осуществляться путем сравнения прототипа.

2022-07-24 17:38 UTC, cuurjol commented on lessons/lesson-4/tasks/task-4.js
> +		if (this.type === 'MotorShipYard' || this.type === 'SailingShipShipYard') {
@PonomareVlad Исправил.

2022-07-24 17:57 UTC, cuurjol commented
@PonomareVlad  Есть главный вопрос к прототипам. Как всё-таки нужно правильно делать иерархию наследования прототипов? Я покажу пару примеров внизу:
```javascript
// Первый вариант:
const Rectangle = function(width, height) {
  this.width = width
  this.height = height
  this.perimeter = () => (2 * (this.width + this.height))
  this.area = () => (this.width * this.height)
}

const Square = function(size) {
  Rectangle.call(this, size, size)
}

Object.setPrototypeOf(Square.prototype, Rectangle.prototype)



// Второй вариант (синоним первому варианту?):
const Rectangle = function(width, height) {
  this.width = width
  this.height = height
  this.perimeter = () => (2 * (this.width + this.height))
  this.area = () => (this.width * this.height)
}

const Square = function(size) {
  Rectangle.call(this, size, size)
  Object.setPrototypeOf(this.__proto__, Rectangle.prototype)
}



// Третий вариант:
const Rectangle = function(width, height) {
  this.width = width
  this.height = height
  this.perimeter = () => (2 * (this.width + this.height))
  this.area = () => (this.width * this.height)
}

const Square = function(size) {
  Rectangle.call(this, size, size)
}

Square.prototype = Object.create(Rectangle.prototype)
Square.prototype.constructor = Square



// Четвёртый вариант (неправильный вариант?):
const Rectangle = function(width, height) {
  this.width = width
  this.height = height
  this.perimeter = () => (2 * (this.width + this.height))
  this.area = () => (this.width * this.height)
}

const Square = function(size) {
  Object.setPrototypeOf(this, new Rectangle(size, size))
}
```

Первый и второй вариант, как я понял, делают одно и тоже. Если не так, то меня нужно исправить и сказать об этом. Есть третий вариант, она практически делает тоже самое, что первый и второй варианты, за исключением того, что в прототипе появляется свойство `constructor`, который будет равняться функции конструктора `Square`. Четвёртый вариант совершенно сильно отличается от первых трёх вариантов, и я таким способом выполнял задачи 2 и 3 в первой части задания четвёртого урока.

Возьмём пример задачи 3:
```javascript
const Human = function(human) {
	this.name = human.name
	this.lastName = human.lastName
	this.phoneNumber = human.phoneNumber
	this.eat = () => (console.log('Eating'))
	this.sleep = () => (console.log('Sleeping'))
	this.callFriend = () => (console.log('Calling and talking to a friend'))
}

const Employee = function(employee) {
	Object.setPrototypeOf(this, new Human(employee))
	this.position = employee.position
	this.baseSalary = employee.baseSalary
	this.salaryCurrency = employee.salaryCurrency
	this.location = employee.location
	this.department = employee.department
}

const CurrentEmployee = function(currentEmployee) {
	Object.setPrototypeOf(this, new Employee(currentEmployee))
	this.startDate = currentEmployee.startDate
	this.writeReport = () => (console.log('Writing a report'))
	this.organizeMeeting = () => (console.log('Organizing a meeting'))
	this.retire = () => (console.log('Retired'))
	this.startVacation = () => (console.log('On vacation'))
}

const FormerEmployee = function(formerEmployee) {
	Object.setPrototypeOf(this, new Employee(formerEmployee))
	this.endDate = formerEmployee.endDate
}
```

Как видно по моему коду выше, я следовал четвёртому варианту наследования прототипов. Я заметил, что когда я создаю объекты `CurrentEmployee` или `FormerEmployee` через их соответсвующие функции конструкторы, то у меня по итогу создаются объекты, тип которых равен `Human`. Правильно ли вообще так делать в Javascript или нет?

По итогу, мне нужно было сделать так, чтобы типы объектов совпадали с названием функций конструкторов при создании этих объектов. И чтобы добиться этого результата, нужно применить один из первых трёх вариантов выше. Здесь тоже возникает вопрос: Правильно ли вообще так делать в Javascript или нет?

2022-07-28 09:49 UTC, PonomareVlad commented
Благодарю за ожидание, да действительно в лекции не объясняется разница между прямым наследованием объектов и наследованием с сохранением класса конструктора (когда вы видите название класса в отладчике)

Предлагаю сейчас ознакомится с [этой лекцией](https://youtu.be/SzaXTW2qcJE)

2022-07-28 09:51 UTC, PonomareVlad commented
Чуть позже добавлю комментарии по вашим примерам и объясню в чем разница между ними и в каких случаях стоит использовать тот или иной метод наследования

2022-07-28 17:43 UTC, PonomareVlad commented
> Возьмём пример задачи 3:

> Как видно по моему коду выше, я следовал четвёртому варианту наследования прототипов. Я заметил, что когда я создаю объекты `CurrentEmployee` или `FormerEmployee` через их соответсвующие функции конструкторы, то у меня по итогу создаются объекты, тип которых равен `Human`. Правильно ли вообще так делать в Javascript или нет?

В указанном примере, установка прототипа происходит по такой логике:

```js
const Human = function() {} // 1. Возвращаем объект класса Human (с прототипом Human.prototype)

const Employee = function(employee) {
    Object.setPrototypeOf(this, new Human()) // 2. Устанавливаем экземпляр объекта Human как прототип
} // и возвращаем объект, у которого прототипом является экземпляр объекта класса Human (не Employee)

const FormerEmployee = function() {
	Object.setPrototypeOf(this, new Employee()) // 3. Задаем объект с прототипом экземпляра Human
} // и возвращаем объект, в котором прототип это объект, наследующий от объекта, который экземпляр Human
```

Если вывести результат вызова `new FormerEmployee` в консоли, то мы увидим что он является объектом класса `Human`, вместо `FormerEmployee` — это произошло по причине того, что по умолчанию в прототипе конструктора (`FormerEmployee.prototype`) содержится ссылка на функцию конструктор:

```js
FormerEmployee.prototype.constructor === FormerEmployee
```

Именно название этой функции, отладчик (или консоль) отображает в качестве названия класса объекта

По этому, при **прямом** наследовании объектов, в качестве его **класса** будет выводится первое найденое значение свойства `constructor` из цепочки прототипов — что в нашем случае приводит к выводу `Human`, т.к. это ближайший объект, у которого сохранилась ссылка на оригинальный конструктор

2022-07-28 19:10 UTC, PonomareVlad commented
Теперь рассмотрим остальные ваши примеры, и определим какое может быть у них применение:

2022-07-28 19:11 UTC, PonomareVlad commented
### Первый вариант:
```js
const Rectangle = function(width, height) {
  this.width = width
  this.height = height
  this.perimeter = () => (2 * (this.width + this.height))
  this.area = () => (this.width * this.height)
}

const Square = function(size) {
  Rectangle.call(this, size, size) // Вызов функции в контексте текущего объекта (передача this)
}

// Наследование с сохранением прототипа конструктора
Object.setPrototypeOf(Square.prototype, Rectangle.prototype)
```
В результате получаем объект склеенный из двух экземпляров (`Square` и `Rectangle`), имеющий в прототипах цепочку:
```js
/* this */ this
/* this.__proto__ */ Square.prototype
/* this.__proto__.__proto__ */ Rectangle.prototype
/* this.__proto__.__proto__.__proto__ */ Object.prototype
```
И соответственно, он будет иметь класс `Square`, который будет определен из ближайшего прототипа со свойством `constructor`:
```js
this.__proto__.constructor === Square.prototype.constructor
```

2022-07-28 19:47 UTC, PonomareVlad commented
### Второй вариант

> синоним первому варианту?

Да, но установка прототипа происходит не "статически" через свойство `prototype` объекта конструктора (`Square`), а через явное присвоение для возвращаемого объекта

```js
const Rectangle = function(width, height) {
  this.width = width
  this.height = height
  this.perimeter = () => (2 * (this.width + this.height))
  this.area = () => (this.width * this.height)
}

const Square = function(size) {
  Rectangle.call(this, size, size)
  Object.setPrototypeOf(this.__proto__, Rectangle.prototype)
}

const Test = function() {
  Square.call(this, 2)
  Object.setPrototypeOf(this.__proto__, Square.prototype)
}
```

Обратите внимание, что в таком случае, если унаследовать от `Square` таким же способом, то цепочка прототипов будет неполной:

```js
/* this */ {/* ... */}
/* this.__proto__ */ Test.prototype
/* this.__proto__.__proto__ */ Square.prototype
/* this.__proto__.__proto__.__proto__ */ Object.prototype // <— тут должен быть Rectangle.prototype
```

2022-07-28 20:30 UTC, PonomareVlad commented
### Третий вариант:

На самом деле, полностью аналогичен первому и точно также возвращает объект "склеенный" из двух экземпляров

```js
const Rectangle = function(width, height) {
  this.width = width
  this.height = height
  this.perimeter = () => (2 * (this.width + this.height))
  this.area = () => (this.width * this.height)
}

const Square = function(size) {
  Rectangle.call(this, size, size) // Вызов функции в контексте текущего объекта (передача this)
}

// Прототипом конструктора задаем пустой объект, который наследует от прототипа объекта конструктора
Square.prototype = Object.create(Rectangle.prototype)
// т.е. Square.prototype.__proto__ === Rectangle.prototype

// Восстанавливаем ссылку на функцию конструктор
Square.prototype.constructor = Square
// без этого, экземпляры `Square` будут отображаться в консоли как `Rectangle`
```

2022-07-28 21:20 UTC, PonomareVlad commented
### Четвёртый вариант:

> неправильный вариант?

На мой взгляд, самый правильный из всех 🙂 (ну почти)

```js
const Rectangle = function(width, height) {
  this.width = width
  this.height = height
  this.perimeter = () => (2 * (this.width + this.height))
  this.area = () => (this.width * this.height)
}

const Square = function(size) {
  Object.setPrototypeOf(this, new Rectangle(size, size))
}
```
Без лишних слов, посмотрим на цепочку прототипов:
```js
/* this */ new Square()
/* this.__proto__ */ {width, height, perimeter, area} // <— Наконец-то экземпляр класса Rectangle 🎉
/* this.__proto__.__proto__ */ Rectangle.prototype
/* this.__proto__.__proto__.__proto__ */ Object.prototype
```
Только в этом варианте, используется полноценное наследование свойств, от экземпляра прямоугольника к экземпляру квадрата (т.е. сначала мы создали прямоугольник, а потом назначили его прототипом квадрата)

Но назначили так, что непосредственным прототипом квадрата является не объект его конструктора (`Square.prototype`), а сразу экземпляр прямоугольника (`new Rectangle`)

Теперь попробуем совместить этот и второй вариант:
```js
const Rectangle = function(width, height) {
  this.width = width
  this.height = height
  this.perimeter = () => (2 * (this.width + this.height))
  this.area = () => (this.width * this.height)
}

const Square = function(size) {
  // Object.getPrototypeOf(this) вместо устаревшего this.__proto__
  Object.setPrototypeOf(Object.getPrototypeOf(this), new Rectangle(size, size))
}
```
И получаем:
```js
/* this */ new Square() // <- Экземпляр класса Square
/* this.__proto__ */ Square.prototype // <- Восстановили объект его конструктора в цепочке 🔥
/* this.__proto__.__proto__ */ {width, height, perimeter, area} // <— Экземпляр класса Rectangle
/* this.__proto__.__proto__.__proto__ */ Rectangle.prototype // <— И его конструктор замыкает цепочку
/* this.__proto__.__proto__.__proto__.__proto__ */ Object.prototype
```

2022-07-28 22:10 UTC, PonomareVlad commented
### Вывод:

Все проблемы от потребности в передаче параметров к функции конструктору, которая должна вернуть прототип

Более понятной заменой всех перечисленных вариантов может стать:

```js
const Rectangle = function(width, height) {
  this.height = height
  this.width = width
}

Object.assign(Rectangle.prototype, {
  area: function () {return this.width * this.height},
  perimeter: function () {return 2 * (this.width + this.height)}
})

const Square = function(size) {
  this.width = this.height = size
}

Object.setPrototypeOf(Square.prototype, Rectangle.prototype)
```

Где сохраняется аналогичная цепочка наследования (от квадрата к прямоугольнику), но без дополнительного экземпляра прямоугольника, а с использованием только его свойств, путем наследования от объекта его конструктора

При этом, сохраняется возможность вызвать конструктор прямоугольника отдельно, а методы будут общими как для них, так и для любых других предков или наследников

2022-07-28 22:32 UTC, PonomareVlad commented
### Заключение:

Все проблемы от потребности в передаче параметров к функции конструктору, которая должна вернуть прототип

Более понятной заменой всех перечисленных вариантов может стать:

```js
const Rectangle = function(width, height) {
  this.height = height
  this.width = width
}

Object.assign(Rectangle.prototype, {
  area: function () {return this.width * this.height},
  perimeter: function () {return 2 * (this.width + this.height)}
})

const Square = function(size) {
  this.width = this.height = size
}

Object.setPrototypeOf(Square.prototype, Rectangle.prototype)
```

Где сохраняется аналогичная цепочка наследования (от квадрата к прямоугольнику), но без дополнительного экземпляра прямоугольника, а с использованием только его свойств, путем наследования от объекта его конструктора

При этом, сохраняется возможность вызвать конструктор прямоугольника отдельно, а методы будут общими как для них, так и для любых других предков или наследников

2022-07-28 23:02 UTC, PonomareVlad requested changes
Нужно доработать решение

2022-07-28 23:02 UTC, PonomareVlad commented on lessons/lesson-4/tasks/task-4.js
> +	let shipTypes = [Ship, MotorShip, SailingShip]
Прототип верфи не должен знать о всех возможных типах кораблей

2022-07-29 06:59 UTC, cuurjol commented on lessons/lesson-4/tasks/task-4.js
> +	let shipTypes = [Ship, MotorShip, SailingShip]
@PonomareVlad Исправил.

2022-07-29 07:09 UTC, cuurjol commented
@PonomareVlad  За подробные ответы каждого варианта и моих вопросов огромное вам спасибо, более-менее стало понятно, но не до конца. Есть быстрый вопрос к вашему расписанному четвёртому варианту. Есть фрагмент кода - `Object.setPrototypeOf(Object.getPrototypeOf(this), new Rectangle(size, size))`. Какой тип прототипа будет после выполнения `Object.getPrototypeOf(this)`: `Object.prototype` или `Function.prototype`?

2022-07-29 09:50 UTC, PonomareVlad commented
Вызов `Object.getPrototypeOf(this)` в функции конструктора вернет `Square.prototype` — т.е. прототип конструктора, который уже присвоен конструируемому объекту `this`

![Снимок экрана 2022-07-29 в 14 47 35](https://user-images.githubusercontent.com/2877584/181733220-4989de5b-1a92-4e8e-92d5-70cf2bb1e812.png)

2022-07-29 09:53 UTC, PonomareVlad commented on lessons/lesson-4/tasks/task-4.js
> +	let shipTypes = [Ship, MotorShip, SailingShip]
Не исправили 🙂

2022-07-29 09:58 UTC, PonomareVlad requested changes
Нужно еще немного доработать решение

2022-07-29 09:58 UTC, PonomareVlad commented on lessons/lesson-4/tasks/task-4.js
> +		}
В классе верфи `Shipyard` не должны перечисляться все возможные типы верфей или кораблей — о них должны знать только классы этих верфей (наследники)

2022-07-29 09:58 UTC, PonomareVlad commented on lessons/lesson-4/tasks/task-4.js
> +}
т.е. их определение нужно переместить сюда, и судя по коду, вы уже это сделали, осталось только доработать функцию конструктора верфи, чтобы она также брала их отсюда

2022-07-29 10:02 UTC, PonomareVlad commented on lessons/lesson-4/tasks/task-4.js
> +}
[Подсказка](https://github.com/PonomareVlad/Thinknetica/blob/main/4/2.mjs)

2022-07-29 11:13 UTC, cuurjol commented on lessons/lesson-4/tasks/task-4.js
> +		}
@PonomareVlad Исправил.

2022-07-30 11:30 UTC, merged