Release Lesson 6, task 1
cuurjol/thinknetica-js-course pull request #7
Opened 2022-08-02 22:35 UTC by cuurjol

https://thinknetica.teachbase.ru/course_sessions/469919/tasks/230681/take?return_url=/viewer/sessions/469919/tasks/230681

2022-08-04 14:05 UTC, PonomareVlad requested changes

2022-08-04 14:05 UTC, PonomareVlad commented on lessons/lesson-6/task-1.js
> +	element.children.forEach((child) => {
В Safari будет ошибка: 
`TypeError: undefined is not a function (near '...element.children.forEach...')`

2022-08-04 14:05 UTC, PonomareVlad commented on lessons/lesson-6/task-1.js
> +			throw `Не найдено свойство ${key}!`
Исключение выбрасывается для элементов, у которых нет атрибута `data-field`

2022-08-04 14:05 UTC, PonomareVlad commented on lessons/lesson-6/task-2.js
> +			if (item.constructor === String) {
Для определения типа по конструктору, лучше использовать `instanceof`, т.к. свойство `constructor` может быть заменено

2022-08-04 15:31 UTC, cuurjol commented on lessons/lesson-6/task-1.js
> +	element.children.forEach((child) => {
@PonomareVlad Исправил. Удивительно то, что в 2022 году эта [проблема](https://stackoverflow.com/questions/15094886/why-is-foreach-not-working-for-children) осталась, если это конечно проблема.

2022-08-04 15:32 UTC, cuurjol commented on lessons/lesson-6/task-2.js
> +			if (item.constructor === String) {
@PonomareVlad Исправил. Опять же, здесь тоже есть неочевидная [проблема](https://stackoverflow.com/questions/203739/why-does-instanceof-return-false-for-some-literals) , что в результате пришлось таким образом писать код.

2022-08-04 15:33 UTC, cuurjol commented on lessons/lesson-6/task-1.js
> +			throw `Не найдено свойство ${key}!`
@PonomareVlad Исправил.

2022-08-05 07:55 UTC, PonomareVlad commented on lessons/lesson-6/task-1.js
> +	element.children.forEach((child) => {
Говорят, что это не баг а фича 🙂

2022-08-05 07:56 UTC, PonomareVlad approved these changes

2022-08-05 08:29 UTC, merged