Release Lesson 8, task 1
cuurjol/thinknetica-js-course pull request #9
Opened 2022-08-14 16:50 UTC by cuurjol

https://thinknetica.teachbase.ru/course_sessions/469919/tasks/230683/take?return_url=/viewer/sessions/sovremennyy-javascript-06-20/tasks/230683

2022-08-16 08:59 UTC, PonomareVlad requested changes
Нужно проверить соответствие спецификации [`Promise.resolve()`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)

> Если переданное значение является thenable - объект (т.е. имеет метод ["then" method](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/then)), возвращаемый промис будет следовать thenable - объекту, принимая своё состояние; в ином случае возвращаемый промис будет выполнен с переданным значением.

```js
const url = 'https://api.ipify.org?format=json'

Promise.resolve(fetch(url)).then(response => response.json()).then(console.debug) // {ip: ...}

CustomPromise.resolve(fetch(url)).then(response => response.json()).then(console.debug)
// CustomPromise {}
```

2022-08-16 14:32 UTC, cuurjol commented
@PonomareVlad исправил свой код. Есть несколько вопросов:

1. Что значит `thenable - объект`? Если это объект, похожий на этом примере по [ссылке](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve#resolving_thenables_and_throwing_errors), то это очень странный такой объект. То есть, это хэш, ключ которого является `then` и значение у него - это функция.... Это вообще где-то используется в написании JS или это просто пример?
2. У меня в классе есть метод `then(thenCallback, catchCallback)`. Можно ли его как-то переписать по-проще или лучше оставить его так, как я сделал? Я так и не смог придумать способа, как убрать дублирующий код (если данный код является таковым).

2022-08-16 18:32 UTC, PonomareVlad commented
1. Да, **thenable** это просто любой объект у которого есть метод `.then()`. 

Он может не быть настоящим промисом, но в такой конструкции, результат вычислений должен быть идентичным:

```js
const someOperation = {then: (resolver) => resolver("some result")};

const somePromise = Promise.resolve("some result")

someOperation.then(result => console.log(result)

somePromise.then(result => console.log(result)
```

2022-08-16 18:34 UTC, PonomareVlad commented
По второму вопросу смогу ответить позже

2022-08-16 19:17 UTC, cuurjol commented
@PonomareVlad По первому вопросу я понял, спасибо за ответ. По поводу второго вопроса, я тогда жду обратной связи, я надеюсь, что там не придётся целиком класс переделывать.

2022-08-19 14:12 UTC, PonomareVlad commented
По второму вопросу: да, можно например обернуть все условия в один общий блок try...catch и после этого упростить условия

2022-08-19 14:17 UTC, PonomareVlad approved these changes

2022-08-23 14:09 UTC, merged